# Generated by Django 6.0.3 on 2026-03-10 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chais/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('MT', 'MASALA TEA'), ('LT', 'LEMON TEA'), ('NT', 'NORMAL TEA'), ('BT', 'BLACK TEA')], max_length=2)),
            ],
        ),
    ]
