# Generated by Django 6.0.3 on 2026-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='chais/'),
        ),
    ]
