# Generated by Django 6.0.3 on 2026-03-11 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_chaireview_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='chai_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=10)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validate', models.DateTimeField()),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='menu.chaivariety')),
            ],
        ),
    ]
