# Generated by Django 6.0.3 on 2026-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('eadd', models.CharField(max_length=50)),
                ('erank', models.IntegerField()),
                ('ecoll', models.CharField(max_length=50)),
            ],
        ),
    ]
